fraud_dwh:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT', 'AGREMWF-RQ59577') }}"
      user: "{{ env_var('DBT_SNOWFLAKE_USER', 'SALLAM') }}"
      password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD', '') }}"
      role: ACCOUNTADMIN
      database: FRAUD_DWH
      warehouse: COMPUTE_WH
      schema: DWH
      threads: 4
      client_session_keep_alive: true
